name: Deploy to GitHub Pages (versioned)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract tag
        id: vars
        shell: bash
        run: |
          if [[ -n "${{ github.event.release.tag_name }}" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi

      - name: Prepare site content
        shell: bash
        run: |
          set -e
          rm -rf build
          mkdir -p build
          cp -R index.html ru en build/

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy versioned site and rebuild versions.json
        shell: bash
        run: |
          set -e
          TAG="${{ steps.vars.outputs.tag }}"
          mkdir -p "gh-pages/v${TAG}"
          cp -R build/* "gh-pages/v${TAG}/"

          cd gh-pages
          VERS=$(ls -1d v*/ 2>/dev/null | sed 's#/##' | sed 's/^v//' | sort -Vr || true)

          {
            echo "["
            first=1
            for v in $VERS; do
              if [ $first -eq 0 ]; then echo ","; fi
              printf '  "%s"' "$v"
              first=0
            done
            echo
            echo "]"
          } > versions.json

      - name: Copy root index (pre-made file) to gh-pages
        shell: bash
        run: |
          cp -f root_index.html gh-pages/index.html

      - name: Commit and push to gh-pages
        shell: bash
        run: |
          set -e
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Publish version v${{ steps.vars.outputs.tag }}" || echo "Nothing to commit"
          git push origin gh-pages